[package]
name = "hypercube-engine"
description = "An in-memory multidimensional analytics engine over live data"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme = "../../README.md"
keywords = ["analytics", "streaming", "linear-algebra", "hypercube"]
categories = ["data-structures", "science"]

[lib]
name = "hypercube"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
hypercube-slice = { path = "../hypercube-slice", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
crossterm = "0.29"
tempfile = "3.14"
